### ISSUE TITLE
node_modules/ng-swipe-to-delete/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectorDef'

### ISSUE THREAD

**Issue by JayasimhaJay1994** [ShankyTiwari/ng-swipe-to-delete#7]
Hi while using the "NgSwipeToDeleteModule" in appmodule i am getting the below issue. Any body knows about this issue?

node_modules/ng-swipe-to-delete/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectorDef'

Global versions:
===========
Angular CLI: 8.3.6
Node: 12.11.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.803.6
@angular-devkit/core         8.3.6
@angular-devkit/schematics   8.3.6
@schematics/angular          8.3.6
@schematics/update           0.803.6
rxjs                         6.4.0

**Comment by davidzwa** [comment]
Currently updating the package to angular 10, should fix the problem you experience.

**Comment by davidzwa** [comment]
See #8

**Comment by davidzwa** [comment]
@JayasimhaJay1994 let me know if Angular 8 is a requirement. If so, we have some slight adjustment to do (although I do advise usage of Ivy/angular 9/10!)

**Comment by JayasimhaJay1994** [comment]
@davidzwa we are upgrading to angular 9. thank you for u r assistance.
